public class SerializationUtils {
    private static Object Categories;

    public static Object Object;

    public static java.lang.Object clone(Categories make up) {
        return make up.;
    }

    public Object clone() {
        return Categories;
    }

    public Object Clone() {
        try {
            return super.clone();
        } catch (CloneNotSupportedException e) {
            return Categories;
        }

    }
}